export const LOGIN_INIT = 'LOGIN_INIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';

export const FETCH_PRESCRIPTIONS_INIT = 'FETCH_PRESCRIPTIONS_INIT';
export const FETCH_PRESCRIPTIONS_SUCCESS = 'FETCH_PRESCRIPTIONS_SUCCESS';
export const FETCH_PRESCRIPTIONS_ERROR = 'FETCH_PRESCRIPTIONS_ERROR';

export const REQUEST_PRESCRIPTIONS_INIT = 'REQUEST_PRESCRIPTIONS_INIT';
export const REQUEST_PRESCRIPTIONS_SUCCESS = 'REQUEST_PRESCRIPTIONS_SUCCESS';
export const REQUEST_PRESCRIPTIONS_ERROR = 'REQUEST_PRESCRIPTIONS_ERROR';

export const APPROVE_PRESCRIPTIONS_INIT = 'APPROVE_PRESCRIPTIONS_INIT';
export const APPROVE_PRESCRIPTIONS_SUCCESS = 'APPROVE_PRESCRIPTIONS_SUCCESS';
export const APPROVE_PRESCRIPTIONS_ERROR = 'APPROVE_PRESCRIPTIONS_ERROR';

export const CREATE_PRESCRIPTIONS_INIT = 'CREATE_PRESCRIPTIONS_INIT';
export const CREATE_PRESCRIPTIONS_SUCCESS = 'CREATE_PRESCRIPTIONS_SUCCESS';
export const CREATE_PRESCRIPTIONS_ERROR = 'CREATE_PRESCRIPTIONS_ERROR';
